---
title: "Rational curiosity predicts the dynamics of habituation and dishabituation in infants and adults"
author: "Your Name"
date: "2023-11-13"
bibliography: library.bib
output:
  bookdown::pdf_book:
    citation_package: biblatex
    keep_tex: true
---


```{r}
library(tidyverse)
library(here)
library(lme4)
library(lmerTest)
library(broom.mixed)
library(magrittr)
library(pbkrtest)
```


```{r}
#Load packages & datasets
library(tidyverse)
library(here)
library(lme4)
library(lmerTest)
library(broom.mixed)
library(magrittr)
library(pbkrtest)

infant_d <- read_csv(here("data/infants/infant_processed_data.csv"))
```
```{r}
# Load models
model_1a <- readRDS(here("cached_models/infants/model_1a.rds"))
model_2a<- readRDS(here("cached_models/infants/model_2a.rds"))
model_2b<- readRDS( here("cached_models/infants/model_2b.rds"))
model_2c <- readRDS( here("cached_models/infants/model_2c.rds"))
model_2d <- readRDS(here("cached_models/infants/model_2d.rds"))
model_3a <- readRDS(here("cached_models/infants/model_3a.rds"))
model_3b <- readRDS(here("cached_models/infants/model_3b.rds"))
model_3c <- readRDS( here("cached_models/infants/model_3c.rds"))

```


# Abstract
```{r child = "01_abstract.Rmd"}

```

# Introduction 
```{r child = "02_introduction.Rmd"}

```

# Rational Action, Nosy Choice for Habituation model
```{r child = "03_RANCH.Rmd"}

```

# RANCH predicts habituation and dishabituation in relation to exposure duration
#```{r child = "04_experiment1.Rmd"}

#```

## Methods

# ```{r child = "04_experiment2_methods.Rmd"}
# ```

## Results

# ```{r child = "05_experiment2_results.Rmd"}
# ```

# Discussion 

# ```{r child = "06_general_discussion.Rmd"}
# ```

# References 



\setlength{\parindent}{-0.1in} 
\setlength{\leftskip}{0.125in}
\noindent