From birth, humans engage in active learning. Even before they gain independent mobility, infants make choices about what to look at and when to stop looking [@haith1980rules; @raz2020learning]. Developmental psychologists have both studied this process of visual decision-making as a phenomenon itself and also relied on it as a key methodological tool. Two key phenomena have been especially important: habituation and dishabituation. Habituation occurs when infants show reduced interest upon repeated exposure to the same stimulus, whereas dishabituation entails renewed interest following the subsequent introduction of a novel stimulus. Dishabituation, also known as novelty preference, is often leveraged to infer infants' perceptual and cognitive abilities [@aslin2007s; @baillargeon1985object; @fantz1963pattern]: in order for an infant to dishabituate, they must distinguish between the original stimulus and the novel one. Despite the robust documentation of habituation and dishabituation in the literature, the mechanisms underlying these changes in gaze duration remain poorly understood. In this paper, we bridge this gap by introducing a rational model of habituation and dishabituation. We show that this rational model makes quantitative predictions of looking times toward different stimuli. 

```{r conceptual, echo=FALSE, fig.width=20, fig.height=7, fig.cap="Conceptual models of looking to novel vs. familiar items according to three models of infant attention: A) The partial encoding model proposed by Hunter and Ames (1988) which suggests a shift from familiarity to novelty preferences, B) The Goldilocks model proposed by Kidd et al. (2012) which suggests that infants prefer to attend to intermediately surprising events, and C) the ‘optimal curiosity’ model introduced by Cao et al. (2023) which suggests that infants are maximizing expected information gain from noisy perceptual samples."}
img <- png::readPNG("figs/conceptual_fig.png")
grid::grid.raster(img)
```

An important early conceptual model of infant looking time posited that habituation and dishabituation are influenced by the amount of information to be encoded by the infant from the stimulus [@hunter1988multifactor]. Initially, infants are assumed to look longer at stimuli containing substantial unprocessed information, showing a familiarity preference (Figure \@ref(fig:conceptual)A). As exposure accumulates, less information remains unprocessed, leading to shorter looking time at the original stimulus and by comparison, relatively longer looking time to a new stimulus (i.e. novelty preference). While this model has had significant influence, the absence of specifications regarding the encoding process or a way of measuring the amount of information to be encoded in a stimulus have both permitted post-hoc explanations of variable looking time measurements. For instance, when infants are looking longer at stimulus A than stimulus B, researchers could interpret the looking time difference as either a novelty preference or a familiarity preference. This interpretive ambiguity has spurred repeated concerns regarding whether looking time measurements should form the basis for key assertions in developmental psychology [@blumberg2023protracted; @haith1998put; @paulus2022should]. In other words, developmental psychology needs formal models that make quantitative predictions, beyond the qualitative foundations of @hunter1988multifactor.

Recent computational models aim to formalize the mechanisms underlying looking time changes. One family of models characterize infants' looking behaviors through information-theoretic metrics derived from ideal observer models: the models acquire probability distributions from event sequences and derive information-theoretic measures from the ideal learner’s belief before and after each event [@kidd2012goldilocks; @poli2020infants; @poli2023eight]. For instance, @kidd2012goldilocks found that an ideal learner's surprisal at an event was related to infants’ looking behavior via a U-shaped curve: infants were least likely to look away when the surprisal of the event was neither too high nor too low (\@ref(fig:conceptual)B, model predictions derived in \@ref(fig:goldilocks-explanation)). 

While these models provide quantitative fits to variation in looking time, they are not models of how an agent makes the decisions of whether to keep looking at the same stimulus or to look at something else. Rather than producing the target behavior directly, these models describe correlations between model-derived, information-theoretic measures and infants' overall looking towards whole sequences of events. Relatedly, these models do not explain why infants would ever look at one single stimulus for a long time, rather than encode it instantaneously -- there is no account of perceptual noise to be overcome by taking multiple perceptual samples that would justify why looking extends over time [c.f. @callaway2021fixation; @kersten2004object]. Owing to this constraint, these models can only be used to predict infant behavior in a specific paradigm: looking to a continuous stream of discrete stimuli. This paradigm deviates significantly from the more common paradigm in which infants gradually encoded individual objects or events in a self-paced manner. Thus, existing models are challenging to generalize to more common looking time paradigms.

To address these issues, we developed the Rational Action, Noisy Choice for Habituation (RANCH) model [@cao2023habituation]. RANCH describes an agent’s looking behavior as rational exploration based on a sequence of noisy perceptual samples. The model construes the looking time paradigm as a series of binary decisions: to keep sampling from the current stimulus, or to look at anything else. The model makes sampling decisions based on the Expected Information Gain (EIG) of the upcoming perceptual sample, choosing to keep looking or look away based on which one would in expectation yield the most information. The RANCH model is therefore a rational analysis of looking behavior [@lieder2020resource; @oaksford1994rational; @anderson1991human]: looking is analyzed as optimally adapted to the environment, given specific constraints on processing (e.g. perceptual noise).

Previously, we validated this rational analysis using a large dataset of adults engaging in a self-paced looking paradigm. We asked adults to look at sequences of stimuli consisting of a repeating familiar background stimulus (resulting in habituation), and a single, novel deviant stimulus after varying familiarization durations (resulting in dishabituation). Effects of prior exposure and novelty on adults' looking time were well captured by RANCH [@cao2023habituation]. Figure \@ref(fig:conceptual)C shows schematic predictions of RANCH for the experimental setting described above: variable prior exposure to a familiar stimulus, followed by a novel or a familiar stimulus. Rational exploration of a simple perceptual concept results in a monotonic decrease of attention to familiar items as a function of prior exposure.

In our work, we address three challenges to adjudicate between the candidate models of infant looking in Figure \@ref(fig:conceptual). A first critical challenge for differentiating formal theories of looking time in infants is that looking time measurements are noisy, and many infant experiments provide only limited precision in their estimates of key quantities \autocite{cristia2016test,debolt2020robust}. In the current work, we develop a novel, within-subject experimental design that allows us to sensitively measure infants' looking time in experiments. In our first experiment, we use this paradigm to measure the dynamics of habituation and dishabituation across different amounts of exposure to a stimulus. Beyond validating RANCH's predictions in infants, this paradigm enables us to conduct interpretable developmental comparisons of parameter fits between infants and adults -- since we can conduct matched experiments in adults -- thereby characterizing what aspects of the processes underlying looking time may change over development.

A second critical challenge for differentiating theories has been their stimulus-dependence. Infancy researchers can rarely make quantitative predictions about differences between stimuli; even previous computational models have relied on using arbitrary representations that are not directly generated from the stimulus materials [e.g. object location, @kidd2012goldilocks; hand-specified binary feature vector, @cao2023habituation]. To address this issue, we incorporated recent progress in convolutional neural networks (CNNs) to allow RANCH to learn from raw images. The representations of many trained CNNs show striking similarities to how primate brains respond to stimuli, and investigating the representations of CNNs has therefore offered insights into how the visual system encodes objects [@doshi2023cortical; @hebart2020revealing; @yamins2014performance]. The activations of these brain-inspired neural networks form embedding spaces, each of which can be seen as a quantitative hypothesis about how humans embed objects in a lower-dimensional perceptual space [@schrimpf2020integrative]. In RANCH, we leveraged these principled stimulus representations to enable RANCH to learn from raw images. In other words, RANCH can `see' an experiment in a way similar to the one infants saw, and make predictions for previously unseen experiments using novel stimuli.

A final challenge is the generalizability of models to new contexts. Because RANCH can be applied across stimulus sets without additional assumptions, we are able to test its predictions in a new dataset. To conduct these tests, we first fit RANCH’s parameters to a training data set from the initial habituation-dishabituation experiment. Then, we use the best-fitting parameters to generate predictions for a new experiment designed to measure differences in dishabituation magnitude. In this experiment, we systematically varied the similarity between habituation and dishabituation stimuli such that dishabituation stimuli differed in their pose angle, their number, their identity, or their animacy. This experiment tests a prediction from @hunter1988multifactor model of habituation and dishabituation: that observers’ dishabituation magnitude should be related to the similarity between the habituated stimulus and the novel stimulus. The more dissimilar two stimuli are, the more one should dishabituate to the novel stimulus.

Addressing these challenges allowed us to compare the different accounts of habituation and dishabituation in \@ref(fig:conceptual) empirically. To preview our results, we find that RANCH provided the best description of behavior in our first experiment, in which we systematically vary prior exposure to a stimulus before measuring looking time to either the same, familiar stimulus or a novel stimulus. Fitting RANCH to infant and adult data separately and comparing the best-fitting parameters revealed that infants' learning was tuned for noisier processing than adults. Then, using these best fitting parameters, we generate predictions for a novel task in which we vary the similarity between the familiar and novel stimulus, and find that RANCH generalizes to a novel task context by predicting the dishabituation magnitude as a function of stimulus dissimilarity. Together, we provide evidence that habituation and dishabituation are well described by a rational analysis of looking time. 