The Rational Action, Noisy Choice for Habituation model (RANCH) is a Bayesian perception and action model in which a learning model is used to derive optimal perceptual sampling decisions [@cao2023habituation]. In RANCH, the learning problem in habituation is conceptualized as learning a visual concept -- a single representation underlying a group of observed stimuli. The model learns by observing a series of noisy perceptual samples from each stimulus. During learning, the model makes decisions about how many samples to receive from each stimulus before moving to the next stimulus. We treat the number of samples for each stimulus as being linearly related to looking time duration.

RANCH provides a probabilistic framework for making perceptual decisions. In this section, we will describe the three modular components of RANCH: the perceptual representation, learning model, and decision model. 

## Perceptual representations 
We use the deep convolutional neural network (CNN) ResNet-50 to encode the stimuli used in behavioral experiments. ResNet-50 is a standard architecture that is widely used in computer vision as well as in comparisons to human behavior [@he2016deep; @lee2023empirical]. A total of 50 layers are implemented in this architecture: it starts with a convolution layer, includes several groups of residual blocks that help preserve information through the network, and ends with a global average pooling layer and a fully connected layer for classification. We used a version of ResNet-50 that was pretrained on ImageNet [@deng2009imagenet]. Training on ImageNet optimizes the Resnet-50's activations for image classification, and we can use these activations as an perceptual "embedding space". When we pass new stimuli through a pre-trained network, we extract these activations to obtain principled embeddings of stimuli (Figure \@ref(fig:RANCH)A). We used the first three principal components of the embedding space to limit the dimensionality of the downstream learning problem. 

^[ResNet-50 is by no means the only possible method for deriving perceptual representations; instead it is a simple, standard choice. We also explored alternative models, such as a CNN trained on egocentric videos from the child's perspective and CNN whose representations were aligned to human categorization behavior [@orhan2024learning; @lee2022rapid]. However, we did not find substantial differences between the embedding spaces provided by ResNet-50 and other (often more complicated) models (Figure \@ref(fig:embedding-distances)).]

## Learning model
RANCH models looking behaviors in habituation experiments as Bayesian concept learning [@goodman2008rational; @tenenbaum1999bayesian]. The model infers the concept that is most likely to have generated a series of noisy perceptual samples taken from a sequence of stimuli. The concept to be learned is a multivariate normal distribution parameterized by  \(\mu,\sigma\), which represents beliefs about the location and variance of the presented concept in the embedding space. The concept \(\mu,\sigma\) generates exemplars \(y\), which is equivalent to the stimulus seen by the human participants. But RANCH does not directly learn from the stimulus. Instead, it learns from the series of noisy perceptual samples \(\bar{z}\) generated by the exemplar. The noisy perceptual sample is corrupted by zero-mean gaussian noise, represented by \(\epsilon\). A plate diagram is shown in Figure \@ref(fig:RANCH)B. At each time step, the model takes one perceptual sample to update the prior following Bayes Rule: 

$$p(\mu, \sigma | \bar{z}) = \frac{p(\bar{z} | \mu, \sigma) * p(\mu, \sigma)}{p(\bar{z})}$$

## Decision model and linking hypothesis

The Bayesian learning model does not address how the model decides to keep sampling the same stimulus or to move on to the next stimulus.To make this decision, RANCH uses the the expected information gain (EIG) of the next perceptual sample. EIG is a metric used under the rational analysis of information-seeking behavior [@anderson1991human; @oaksford1994rational], and is computed as the expected value of the KL divergence between the hypothetical posterior at the next timepoint $t+1$ and the current posterior. Formally: $EIG = \mathbb{E_{t+1}}(KL(P(\mu,\sigma|z_{t+1}), P(\mu,\sigma|z_{t})))$. RANCH then uses a softmax choice (with temperature = 1) between the information theoretic measures of the next sample and a constant, which is assumed to represent the amount of information gain provided by the environment when the learner looks away from the stimulus. An algorithm table describing the overall sampling procedure is shown in Figure \@ref(fig:RANCH)C.

```{r RANCH, echo = FALSE, fig.env = "figure", fig.width=20, fig.height=7, set.cap.width=T, num.cols.cap=1, fig.cap = "Three components of RANCH: A) Perceptual representation: stimulus embeddings from ResNet-50 final layer activations, B) Learning model: plate diagram for Gaussian concept learning from noisy observations, C) Decision model: RANCH repeatedly samples until environmental EIG outweighs EIG from another sample."}
img <- png::readPNG("figs/RANCH_fig.png")
grid::grid.raster(img)
```

## Implementation
RANCH has free parameters including the learner’s priors over the concept to be learned ($\mu$, $\sigma$), the learner’s priors over their perceptual noise ($\sigma_{\epsilon}$) and the constant representing EIG from the environment ($EIG_{env}$). We conducted an iterative grid search over these parameters.

While gaussian concept learning models can be computed analytically, hierarchical models that include perceptual noise must be approximated via sampling methods. We used grid approximation, creating discrete grids over $\mu$, $sigma$, $y$ (exemplars) and $z$ (noisy samples) to perform inference. We further used a grid over possible next observations when computing EIG. 

To remove noise resulting from this grid approximation, we averaged each stimulus and parameter setting over 100 runs. To avoid bias, these 100 simulations used 20 different ``jitters'' - such that the exact location of the points in the discrete grids was randomly chosen. We used the number of samples the model decided to take from each stimulus as a proxy for looking time. We then averaged this metric across the 100 runs.

This process required significant computational resources. The grid approximation, combined with repeated simulations, demanded high-performance cluster GPUs to perform vectorized computation using a PyTorch implementation of our model. Running a single parameter setting through an experiment took approximately 10 hours on a GPU. By distributing different parameter settings across ~15 GPUs, a full parameter search took about 3 days of compute.

