```{r, include=FALSE}
# sample sizes & ages
n_zoom = exp2_zoom_infant_d %>% pull(subject_num) %>% unique() %>% length()
m_zoom_age = exp2_zoom_infant_d %>% group_by(subject_num) %>% summarize(age = mean(age)) %>% pull(age) %>% mean() %>% round(2)
n_lookit = exp2_lookit_infant_d %>% pull(subject_num) %>% unique() %>% length()
m_lookit_age = exp2_lookit_infant_d %>% group_by(subject_num) %>% summarize(age = mean(age)) %>% pull(age) %>% mean() %>% round(2)
n_control = exp2_control_infant_d %>% pull(SubjectInfo.subjID) %>% unique() %>% length()
m_control_age = exp2_control_infant_d %>% group_by(SubjectInfo.subjID) %>% summarize(age = mean(SubjectInfo.testAge)) %>% pull(age) %>% mean() %>% round(2)

# stats models
exp2_zoom_infant_d$test_type = relevel(as.factor(exp2_zoom_infant_d$test_type), ref = "background")
model_zoom <- lmer(log(LT) ~ log(block_num) + test_type + (1|subject_num), data = exp2_zoom_infant_d)
model_zoom <- tidy(model_zoom) %>% mutate_if(is.numeric, round, 2)

exp2_lookit_infant_d$violation_type = relevel(as.factor(exp2_lookit_infant_d$violation_type), ref = "background")
model_lookit <- lmer(log(LT) ~ log(block_num) + violation_type + (1|subject_num), data = exp2_lookit_infant_d)
model_lookit <- tidy(model_lookit) %>% mutate_if(is.numeric, round, 2)

# Exclusions



```



Beyond predicting non-linearities in attentional preferences during encoding (Fig. 1B), @hunter1988multifactor also predicted that after complete encoding of a stimulus,dishabituation magnitude should be linked to the similarity between two stimuli: the more dissimilar the novel stimulus is to the habituation stimulus, the more participants should dishabituate. We designed an experiment testing the relationship between stimuli similarity and dishabituation magnitude by systematically varying the similarity between the familiar stimuli and the novel stimuli. Instantiating RANCH provides an explicit notion of similarity through the use of ResNet50-derived image embeddings. We can therefore test whether RANCH also predicts such similarity-based differences in dishabituation magnitude. We showed that the best-fitting parameters trained from the previous behaviors predict infants and adults behaviors in the new experiment. In other words, RANCH is capable of making out-of-sample predictions about novel behaviors that it was not trained on.

## Behavioral Experiment

### Infant experiment 
To study whether infants show similarity-based dishabituation between the habituation and novel stimulus, we ran an experiment via Zoom (n=`r n_zoom`, age range=7-10 months, $M_{age}$=`r m_zoom_age/30`months), and an exact replication via Lookit (n =`r n_lookit`, age range=6-12 months, $M_{age}$=`r m_lookit_age/30`months). We presented infants with a series of blocks, each again consisting of a familiarization and a test trial (Figure \@ref(fig:design), Experiment 2, Infants). Instead of modifying prior exposure as in the previous experiment, here infants were always familiarized 8 or 9 times with an animal (corresponding to the amount of exposure that caused robust dishabituation in the previous experiment). After familiarization, infants saw a test trial, which could relate to the familiar animal in one of five ways: they either saw the same animal again (background), the same animal facing in the opposite direction (pose), a different animal facing the same way (identity), two instances of the same animal side-by-side (number), or an inanimate vegetable or fruit (animacy). In a control experiment, we tested baseline interest in these stimuli without prior familiarization, to ensure that condition differences in the main experiments are due to violations, rather than intrinsic to the stimuli (n=`r n_control`, age range=7-10 months, $M_{age}$=`r m_control_age/30`months).

### Adult experiment 
This adult experiment was procedurally similar to the previous experiment and has similar adaptation to the infant experiment. Participants (N = 468) saw a sequence of animation, with repeating stimulus and one novel stimulus that appears at the end of the sequence. Since adults have longer attention span, we can test adults in all permutations of the familiar stimulus and novel stimulus. The familiar stimuli were either animals or vegetables, facing eighth left or right, coming in either one or a pair. Like the infant experiment, the novel stimulus can be different from the familiar stimulus in one of the four ways: pose, identity, number, or animacy. 


## Model Evaluation

We successfully captured similarity-based dishabituation in both infants and adults: 
Similar to the previous experiment, infants showed dishabituation to all novel test trials (identity: $\beta$ = `r filter(model_zoom, term == "test_typeidentity")$estimate`; *SE* = `r filter(model_zoom, term == "test_typeidentity")$std.error`; *t* = `r filter(model_zoom, term == "test_typeidentity")$statistic`; *p* = `r  filter(model_zoom, term == "test_typeidentity")$p.value`, number: $\beta$ = `r filter(model_zoom, term == "test_typenumber")$estimate`; *SE* = `r filter(model_zoom, term == "test_typenumber")$std.error`; *t* = `r filter(model_zoom, term == "test_typenumber")$statistic`; *p* = `r  filter(model_zoom, term == "test_typenumber")$p.value`, animacy: $\beta$ = `r filter(model_zoom, term == "test_typeanimacy")$estimate`; *SE* = `r filter(model_zoom, term == "test_typeanimacy")$std.error`; *t* = `r filter(model_zoom, term == "test_typeanimacy")$statistic`; *p* = `r  filter(model_zoom, term == "test_typeanimacy")$p.value`), except the pose violation, which elicited no significant dishabituation. There was also evidence that the magnitude of dishabituation was related to the similarity of the novel trial: Infants looking time followed the pre-registered expected ordering: animacy > number > identity > pose > background (Figure REF). A control experiment suggested infants showed no baseline differences in looking time between categories (See SI).

Our exact replication via Lookit showed similar, though not identical results: We again found that animacy and number resulted in the strongest dishabituation in infants, and pose violations did not elicit dishabituation. However, unlike the Zoom study, the identity violation did not elicit significant dishabituation in our Lookit study  ^[Note that we pre-registered the identity violation as a data quality check, since we had replicated that effect in both infant experiments. However, surprisingly, the identity condition was the only condition that differed from the Zoom experiment, so here we deviate from pre-registration and report these Lookit findings regardless given the high value of having a second sample of infant data.]. We suggest potential reasons in the general discussion.

In adults, like in previous experiments, we found evidence for habituation (STATS). More importantly, we also found evidence for graded dishabituation: the dishabituation magnitude to animacy violations is larger than to number violations (STATS) and to pose violations (STATS). Same pattern was found for identity type novelty (STATS). However, animacy type novelty was not different from identity type novelty, nor was the number type novelty different from the pose type novelty (STATS). Qualitatively, we found that the ordering for dishabituation magnitude was animacy (STATS) > identity (STATS) > pose (STATS) > and number (STATS). 

We next tested whether RANCH made similar predictions. We used the same modeling procedure described in the previous experiment, simulating the infant and adult experiment respectively.  We converted the raw images into the embeddings and assembled the stimuli into the sequences that participants saw in each block. 

Using the previously obtained parameters, we found that RANCH generalized to the new dataset (Adults: STATS; Infants: STATS). Moreover, RANCH also showed a qualitative ordering of the dishabituation magnitude: animacy > identity > number > pose. This ordering was in line with the CNN-derived embedding distances between the different stimulus categories (SI Figure of embedding distances).  

Taken together, though there were some discrepancies between the qualitative ordering between infants, adults and RANCH (discussed below), our analyses show that RANCH is not only capable of capturing habituation and dishabituation, but also can generalize to a new task and make predictions about dishabituation magnitude in relation to stimulus similarity. 
