Measuring habituation and dishabituation has been a key way to gaining insight into the infant mind, but the computational underpinnings are not well understood. Here, we investigated how well these behaviors can be understood as rational exploration of noisy perceptual samples. To do so, we introduced a rational learner model, RANCH, which takes noisy samples from stimuli and makes sampling decisions based on the next sample’s EIG. RANCH makes continuous predictions about infants’ looking times to familiar vs. novel stimuli when varying prior exposure. We found that model fit was robust to parameters, and that KL and EIG provided better model fits than surprisal. Furthermore, lesioned models showed that both the learning and noise components of RANCH were essential to its performance. We also found that the key difference between infants and adults was the learner’s prior on their noise - the model preferred higher noise to fit the infant data than when fitting the adult data. After fitting RANCH to this exposure duration experiment, we also tested its ability to make predictions on a new task, where we varied the way in which a familiar stimulus is violated by changing its pose, number, identity or animacy. We find that, without any new tuning of the model to the new task, RANCH predicts a gradient in the magnitude of dishabituation similar to the gradient observed in looking time data.

## Novel within-subjects designs
To test our model, we developed novel paradigms for within-infant measurements of habituation and dishabituation. These novel designs allowed us to go beyond testing simple qualitative  predictions (i.e. longer versus shorter looking duration). Instead, we validated RANCH’s continuous predictions about the relationship between prior exposure and looking to novel vs. familiar stimuli (Experiment 1) and between perceptual distance and looking (Experiment 2), within subjects. Scaling this approach through remote infant behavior testing and automated gaze coding via iCatcher+ [@erel2023icatcher] has allowed us to collect within-subject data from N infants.

## Graded dishabituation in humans and models
Our findings in Experiment 2 warrants further discussion. In particular, the number violation resulted in interesting patterns across age groups and RANCH: The number of samples RANCH preferred to take from number violations was less than identity violations but more than pose violations, similar to adults. Infants however looked at number violations more than identity violations. This discrepancy between the model and adults on the one hand, and infants on the other hand could be explained by a variety of factors. 

RANCH is designed for representing single objects, not multiple objects, therefore any dishabituation to number violations results primarily from simple, low-level perceptual distances, rather than dishabituation to number per-se. To the extent that the dishabituation observed in the data exceeds RANCH’s, we can say that this points to other, conceptual sources of surprise that cannot be explained purely by low-level visual differences. This is consistent with infant literature showing that infants are sensitive to changes in number specifically, rather than visual changes generally [@wynn1998psychological; @feigenson2004core]. Adults on the other hand did not show this exaggerated effect of number violations, possibly because adults’ processing was shallower in our task, which is supported by their shorter reaction times.

Infants’ stronger dishabituation to number violations than predicted by RANCH was replicated in our Lookit experiment. However, unlike in the original Zoom experiment, the Lookit experiment did not elicit significant dishabituation to identity violations. This is in contrast to our findings in both Experiment 1 and Experiment 2, where identity violations after long familiarizations caused longer looking times than looking to the background. There may be two possible reasons for this discrepancy: First, while in the Zoom study experimenters terminated trials when infants looked away for three seconds, the Lookit experiment used fixed trial durations due to the asynchronous set-up. While in both experiments looking times are still calculated using a standard criterion off-look [@horowitz1972infant], the infant-contingency of the Zoom experiment likely increases the data quality and results in higher sensitivity to smaller effects. Similarly, an experimenter being present via Zoom allows them to ensure a quiet testing environment and adjust the flow of the experiment to the participant - previous comparisons between Zoom and asynchronous studies similarly suggest that effects via Zoom tend to be larger. 

## Unique strengths of RANCH framework
A key strength of RANCH is the cognitive interpretability of its parameters. Previous Bayesian models of infant attention have leveraged parameter interpretability to draw conclusions about the computational mechanisms underlying individual differences in attention [@poli2024individual]. Here, we use parameter fits of RANCH to study population differences: By applying a “joint scaling” procedure in which we scale model samples to infant and adult simultaneously, we could identify which parameters had to be different between infant and adults to account for their different patterns of looking time. Using this procedure, a key developmental difference was in $\sigma_{\epsilon}$, the learner's prior on their perceptual noise. Given that $\sigma_{\epsilon}$ was higher in infants than in adults, this suggests that infants' learning in our experiments may be tuned for noisier perceptual processing.

Another strength is RANCH’s ability to model looking on a more fine-grained timescale. Prior research has largely resorted to modeling on the trial-level, and asking about correlations between behavior on a given trial (e.g. looking time) and certain information-theoretic proxies, such as KL or surprisal [@kidd2012goldilocks; @poli2023eight]. A rational analysis with EIG is not possible at this resolution, because models that carve up time in terms of trials, rather than samples, cannot explicitly represent expected information gain. It is only in moment-by-moment modeling frameworks like RANCH that we can implement the formal rational analysis [@oaksford1994rational; @anderson1991human], in which learners ask “How much information do I expect to gain from taking another sample from the stimulus?”. The ability to conduct the rational analysis enhances our understanding of habituation as optimally adapted to environmental constraints [see e.g. @gershman2024habituation, for a different rational analysis of habituation]. Still, replacing EIG with information-theoretic proxies in our setting can help us examine whether participants’ behavior seems to follow an EIG-based, or a proxy-based, linking hypothesis. In our analyses we found that though KL divergence performed comparably to EIG, the surprisal-based model was worse at fitting both infant and adult data. 

## No evidence for familiarity preferences 
A key feature of our experimental data, as well as our model, is that at no point, even for the shortest familiarization durations, we find longer looking to familiar than to novel stimuli. This finding contrasts with predictions made by a prominent model of infant attention (Figure \@ref(fig:conceptual)A)), which posit that at intermediate levels of encoding, familiar stimuli should be more interesting than novel stimuli. The intuition is that some initial familiarity with a stimulus may allow a viewer to “break into” the information there is to gain from the stimulus - a completely novel stimulus may be too complex or foreign for extended attention to be worth it. In the learning setting of simple perceptual learning, the rational analysis and participants do not seem to favor this strategy. This suggests that limited exposure does not generically lead to familiarity preferences in any experimental paradigm.

Of course, the absence of familiarity preferences in our results does not rule out their existence in general. First, familiarity preferences may be more subtle than novelty preferences, so that the statistical power that is needed to find familiarity preferences is higher than that achieved in the current study. A current large-scale study by the ManyBabies consortium which aims to test the predictions made by @hunter1988multifactor may give insight into this possibility [@kosie2023manybabies]. In addition, the learning problem that participants are solving likely plays a critical role in whether they will exhibit familiarity preferences. This context-dependence is reflected in meta-analyses investigating familiarity preferences in different paradigms. For example, when tested on word segmentation in their native language, infants show persistent preferences for familiar stimuli throughout the first year [@bergmann2016development]. In contrast, when tested on statistical learning of novel words, infants show consistent preferences for novel stimuli, from 4-month- to 11 months of age [@black2017quantifying]. 

## Formal theories of learning and attention
These seemingly contradictory results highlight the need for formal theories of how the learning problem influences attention. @dubey2020reconciling give an example of such a formal account by showing that when past and present events are correlated, rational agents, under some assumptions, develop a tendency to attend to familiar stimuli to prepare for the most likely future events, while in uncorrelated environments, novelty preferences are optimal. On the other hand, ideal learners attempting to maximize their expected information gain consistently seek novelty when trying to learn a single concept. Formal models of the learning problem being solved in experiments may therefore give more principled and precise predictions beyond identifying factors like “prior exposure” as determinants of attentional preferences.

Importantly, RANCH's predictions outlined in this paper apply to the specific case: the learner makes noisy observations of 1) stimuli from a specific embedding space, 2) updates its beliefs about the location of a single concept and 3) makes sampling decisions based on EIG. The modular structure of RANCH allows for each of these components (embedding space, learning model and linking hypothesis) to be modified, likely leading to different predictions. For example, the embedding space could be chosen to more closely resemble a psychologically validated perceptual space [e.g. @lee2022rapid], though in this case, we found that such alternatives did not affect embedding structure qualitatively (Figure \@ref(fig:embedding_distances))). Similarly, the learning problem could be modified to account for more complex, or more general, representation learning [@kemp2008discovery; @tenenbaum2011grow]. For example, in our task participants may not just be learning a single concept, but rather also decide whether a stimulus should prompt the creation of a new concept or not.


## Conclusion
Infants are active learners. From birth, they actively explore their environment through selective attention. Looking time, a widely used measure in developmental psychology, leverages this ability to help make inferences about infants' conceptual and perceptual capacity. However, past literature tends to use looking time measure as a categorical qualitative outcome (e.g.~infants either look longer or shorter at a particular stimuli), rather than a graded, continuous measure (e.g.~how long infants would look at certain stimuli). In our work, we provided strong evidence that looking time is a graded measure and can be predicted quantitatively by a model that posits that infants' looking time is driven by rational curiosity. This work not only puts the methodological foundations of infant looking time research on firmer ground, but also contributes to our understanding of rational exploration behaviors throughout developmental trajectories.
